// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartAC.Data;

namespace SmartAC.Migrations
{
    [DbContext(typeof(DeviceContext))]
    [Migration("20190718010319_Device2")]
    partial class Device2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartAC.Models.DataReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CarbonMonoxideLevel");

                    b.Property<Guid>("DeviceId");

                    b.Property<double>("Humidity");

                    b.Property<DateTime>("ReadingDate");

                    b.Property<Guid>("SensorId");

                    b.Property<string>("Status")
                        .HasMaxLength(150);

                    b.Property<double>("Temperature");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("DataReading");
                });

            modelBuilder.Entity("SmartAC.Models.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50);

                    b.Property<DateTime>("RegistrationDate");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50);

                    b.HasKey("DeviceId");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("SmartAC.Models.Sensor", b =>
                {
                    b.Property<Guid>("SensorId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("DeviceId");

                    b.HasKey("SensorId");

                    b.HasIndex("DeviceId");

                    b.ToTable("Sensor");
                });

            modelBuilder.Entity("SmartAC.Models.DataReading", b =>
                {
                    b.HasOne("SmartAC.Models.Sensor")
                        .WithMany("DataReadings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SmartAC.Models.Sensor", b =>
                {
                    b.HasOne("SmartAC.Models.Device")
                        .WithMany("Sensors")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
